List<Map> categories = [
  {'name': 'Your Story', 'iconPath': 'images/1.jpg'},
  {'name': 'ajith_a_man', 'iconPath': 'images/Ajith.jpg'},
  {'name': 'gkcreation_6', 'iconPath': 'images/Gopi.jpg'},
  {'name': 'kettapaiyan_', 'iconPath': 'images/Aravind.jpg'},
  {'name': 'im_maaran', 'iconPath': 'images/Manimaran.jpg'},
  {'name': 'deepak_ragavan', 'iconPath': 'images/Deepak.jpg'},
  {'name': 'besties_memes_', 'iconPath': 'images/Bestiesmeme.jpg'},
  {'name': 'vadivelu_memes', 'iconPath': 'images/Vadivelu.jpg'},
  {'name': '_chuttikulandhai', 'iconPath': 'images/Chuttikulandhai.jpg'},
  {'name': 'cartoon_memes', 'iconPath': 'images/Cartoon.jpg'},
  {'name': 'photo_shoot_', 'iconPath': 'images/Photoshoot.jpg'},
  {'name': 'pubg_tamilan_', 'iconPath': 'images/Pubg.jpg'},
  {'name': 'photo_shoot_2', 'iconPath': 'images/Photoshoot2.jpg'},
  {'name': 'SK_memes', 'iconPath': 'images/SK_meme.jpg'}
];

List<Map> profiles = [
  {
    'name': 'besties_memes_',
    'iconPath': 'images/Bestiesmeme.jpg',
    'post': 'images/Bestiesmeme.jpg',
    'views': '1024 views',
    'hour': '53 minutes ago',
    'active': '53 minutes ago',
    'like': '1687',
    'comment': '15',
  },
  {
    'name': 'gkcreation_6',
    'iconPath': 'images/Gopi.jpg',
    'post': 'images/Gopi.jpg',
    'views': '3581 views',
    'hour': '2 hours ago',
    'active': '3 minutes ago',
    'like': '1007',
    'comment': '57',
  },
  {
    'name': 'kettapaiyan_',
    'iconPath': 'images/Aravind.jpg',
    'post': 'images/Aravind.jpg',
    'views': '3500 views',
    'hour': '16 hours ago',
    'active': '3 hours ago',
    'like': '4216',
    'comment': '90',
  },
  {
    'name': 'vadivelu_memes',
    'iconPath': 'images/Vadivelu.jpg',
    'post': 'images/Vadivelu.jpg',
    'views': '4201 views',
    'hour': '4 day ago',
    'active': '13 hours ago',
    'like': '143',
    'comment': '12',
  },
  {
    'name': 'ajith_a_man',
    'iconPath': 'images/Ajith.jpg',
    'post': 'images/Ajith.jpg',
    'views': '2406 views',
    'hour': '23 hours ago',
    'active': '1 week ago',
    'like': '3728',
    'comment': '145',
  },
  {
    'name': 'im_maaran',
    'iconPath': 'images/Manimaran.jpg',
    'post': 'images/Manimaran.jpg',
    'views': '4606 views',
    'hour': '1 day ago',
    'active': 'Active now',
    'like': '943',
    'comment': '80',
  },
  {
    'name': '_chuttikulandhai',
    'iconPath': 'images/Chuttikulandhai.jpg',
    'post': 'images/Chuttikulandhai.jpg',
    'views': '4201 views',
    'hour': '4 day ago',
    'active': '6 weeks ago',
    'like': '564',
    'comment': '67',
  },
  {
    'name': 'deepak_ragavan',
    'iconPath': 'images/Deepak.jpg',
    'post': 'images/Deepak.jpg',
    'views': '4201 views',
    'hour': '4 day ago',
    'active': '13 minutes ago',
    'like': '672',
    'comment': '45',
  },
  {
    'name': 'cartoon_memes',
    'iconPath': 'images/Cartoon.jpg',
    'post': 'images/Cartoon.jpg',
    'views': '4201 views',
    'hour': '4 day ago',
    'active': '33 minutes ago',
    'like': '743',
    'comment': '76',
  },
  {
    'name': 'photo_shoot_',
    'iconPath': 'images/Photoshoot.jpg',
    'post': 'images/Photoshoot.jpg',
    'views': '7201 views',
    'hour': '2 day ago',
    'active': '53 minutes ago',
    'like': '5743',
    'comment': '1276',
  },
  {
    'name': 'pubg_tamilan_',
    'iconPath': 'images/Pubg.jpg',
    'post': 'images/Pubg.jpg',
    'views': '201 views',
    'hour': '2 hours ago',
    'active': '3 minutes ago',
    'like': '143',
    'comment': '76',
  },
  {
    'name': 'photo_shoot_2',
    'iconPath': 'images/Photoshoot2.jpg',
    'post': 'images/Photoshoot2.jpg',
    'views': '3201 views',
    'hour': '1 day ago',
    'active': '53 minutes ago',
    'like': '2743',
    'comment': '576',
  },
  {
    'name': 'SK_memes',
    'iconPath': 'images/SK_meme.jpg',
    'post': 'images/SK_meme.jpg',
    'views': '1001 views',
    'hour': '1 day ago',
    'active': '12 minutes ago',
    'like': '843',
    'comment': '296',
  },
];
